In [32]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already up-to-date: sklearn in /Users/nebiatadugna/opt/anaconda3/envs/EnvBootcamp/lib/python3.6/site-packages (0.0)


In [33]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MinMaxScaler

# Read the CSV and Perform Basic Data Cleaning

In [35]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1  FALSE POSITIVE              0              1              0              0   
2  FALSE POSITIVE              0              1              0              0   
3       CONFIRMED              0              0              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4    4.134435     1.050000e-05    -1.050000e-05   172.979370   

   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.003520  ...             -81      4.467           0.064   
1          0.000581  ...            -176      4.544           0.044   
2          0.000115  ...            -174      4.564           0.053   
3          0.001130  ...            -211      4.438           0.070   
4          0.001900  ...            -232      4.486           0.054   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.176     0.868          0.233         -0.078  297.00482   
2          -0.168     0.791          0.201         -0.067  285.53461   
3          -0.210     1.046          0.334         -0.133  288.75488   
4          -0.229     0.972          0.315         -0.105  296.28613   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.134129      15.436  
2  48.285210      15.597  
3  48.226200      15.509  
4  48.224670      15.714  

[5 rows x 41 columns]

# Select your features (columns)

In [36]:
# Set features. This will also be used as your x values.
selected_features = df[df.columns]
selected_features = selected_features.drop(columns = 'koi_disposition')
X = selected_features
y = df['koi_disposition'].to_numpy()
y

array(['CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', ..., 'CANDIDATE',
       'FALSE POSITIVE', 'FALSE POSITIVE'], dtype=object)

In [37]:
columns = selected_features.columns.to_list()

In [38]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [39]:
encoded_y

array([1, 2, 2, ..., 0, 2, 2])

In [40]:
encoded_y = encoded_y.reshape(-1,1)
print(X.shape, y.shape)

(6991, 40) (6991,)


In [41]:
encoded_y.shape

(6991, 1)

# Create a Train Test Split

Use `koi_disposition` for the y values

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, encoded_y_train, encoded_y_test = train_test_split(X, encoded_y, random_state=1)

In [43]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
3563              0              0              0              0   10.548413   
4099              0              0              0              0   24.754385   
5460              0              0              0              0    1.057336   
1091              0              0              0              0  201.118319   
5999              0              0              0              0   91.649983   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
3563     5.470000e-05    -5.470000e-05   139.064020          0.004110   
4099     1.365000e-04    -1.365000e-04   140.207320          0.004460   
5460     1.230000e-07    -1.230000e-07   131.792007          0.000096   
1091     1.461000e-03    -1.461000e-03   187.569860          0.005290   
5999     3.181000e-03    -3.181000e-03   175.715600          0.028600   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
3563         -0.004110  ...            -133      4.387           0.066   
4099         -0.004460  ...            -144      4.519           0.078   
5460         -0.000096  ...            -140      4.594           0.054   
1091         -0.005290  ...            -112      4.447           0.072   
5999         -0.028600  ...            -233      4.145           0.164   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
3563          -0.123     1.092          0.181         -0.097  298.09543   
4099          -0.052     0.804          0.056         -0.076  295.73535   
5460          -0.027     0.683          0.054         -0.060  292.18417   
1091          -0.108     0.954          0.135         -0.083  283.11377   
5999          -0.164     1.608          0.905         -0.383  294.93198   

            dec  koi_kepmag  
3563  44.737061      13.204  
4099  42.576248      15.514  
5460  49.310040      15.414  
1091  48.131390      13.328  
5999  39.812420      12.964  

[5 rows x 40 columns]

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [44]:
# Scale your data
X_scaler=MinMaxScaler().fit(X_train)
X_scaled_train=X_scaler.transform(X_train)
X_scaled_test=X_scaler.transform(X_test)

/Users/nebiatadugna/opt/anaconda3/envs/EnvBootcamp/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [45]:
X_scaled_train

array([[0.        , 0.        , 0.        , ..., 0.83497297, 0.51779124,
        0.5155798 ],
       [0.        , 0.        , 0.        , ..., 0.72693168, 0.38067188,
        0.70650467],
       [0.        , 0.        , 0.        , ..., 0.56436342, 0.80798012,
        0.69823952],
       ...,
       [0.        , 0.        , 1.        , ..., 0.88419373, 0.2724652 ,
        0.74055707],
       [0.        , 0.        , 0.        , ..., 0.38035748, 0.58629009,
        0.733697  ],
       [0.        , 0.        , 0.        , ..., 0.25722845, 0.72706515,
        0.59980164]])

In [46]:
encoded_y_train.ravel()

array([0, 1, 0, ..., 2, 1, 1])

In [47]:
print(X_scaled_train.shape, encoded_y_train.shape)

(5243, 40) (5243, 1)


# Train the Model



In [48]:
encoded_y_train = encoded_y_train.ravel()

In [49]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model2 = SVC(kernel='linear')
model2.fit(X_scaled_train, encoded_y_train.ravel())
lsvc = model2.fit(X_scaled_train, encoded_y_train.ravel())

In [50]:
print(f"Training Data Score: {model2.score(X_scaled_train, encoded_y_train)}")
print(f"Testing Data Score: {model2.score(X_scaled_test, encoded_y_test)}")

Training Data Score: 0.8374976158687775
Testing Data Score: 0.8558352402745996


In [51]:
model2.coef_[0]

array([-1.30294958e+00,  8.60750368e-01, -1.31718082e+00,  0.00000000e+00,
        3.47132962e+00,  1.42383353e+00, -1.42383353e+00, -1.20037339e+00,
        6.10373209e+00, -6.10373209e+00,  2.47405986e-01,  2.39974987e+00,
        4.16339225e-01, -3.39745247e+00,  6.10230899e+00, -6.10230899e+00,
        8.02542324e-01,  2.53931916e-02, -2.53931916e-02,  7.70061301e-03,
        2.32834342e-02, -5.22695989e-03,  2.65925684e+00,  1.85586924e-02,
        4.70847327e-02, -1.67022791e-02, -2.19507543e+00, -8.89285642e-01,
       -2.36660985e+00,  5.30701333e+00, -3.78752948e+00, -2.96982997e+00,
       -7.80724937e-01, -2.45561891e+00,  6.50944639e-01,  1.31261478e+00,
       -3.91450233e-01,  4.24050115e-01, -4.35333365e-01, -1.15365197e-01])

In [52]:
print(model2.coef_, columns)

[[-1.30294958e+00  8.60750368e-01 -1.31718082e+00  0.00000000e+00
   3.47132962e+00  1.42383353e+00 -1.42383353e+00 -1.20037339e+00
   6.10373209e+00 -6.10373209e+00  2.47405986e-01  2.39974987e+00
   4.16339225e-01 -3.39745247e+00  6.10230899e+00 -6.10230899e+00
   8.02542324e-01  2.53931916e-02 -2.53931916e-02  7.70061301e-03
   2.32834342e-02 -5.22695989e-03  2.65925684e+00  1.85586924e-02
   4.70847327e-02 -1.67022791e-02 -2.19507543e+00 -8.89285642e-01
  -2.36660985e+00  5.30701333e+00 -3.78752948e+00 -2.96982997e+00
  -7.80724937e-01 -2.45561891e+00  6.50944639e-01  1.31261478e+00
  -3.91450233e-01  4.24050115e-01 -4.35333365e-01 -1.15365197e-01]
 [-2.00045436e+00 -2.00032046e+00 -2.00054543e+00 -2.00085771e+00
   5.12124962e-05  6.43812021e-06 -6.43812021e-06 -1.00302376e-04
   1.35166905e-04 -1.35166905e-04  3.74313461e-04 -1.72962314e-04
   4.85156790e-04 -5.21517166e-04 -6.12243362e-04  6.12243362e-04
  -1.54686554e-05  2.14070637e-04 -2.14070637e-04 -3.90281784e-03
   1.7270

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [53]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [500,600, 700, 800 ,1000, 1100, 1200, 1300],
              'gamma': [1e-16, 1e-15,1e-14,1e-13]}
grid2 = GridSearchCV(model2, param_grid, n_jobs = 10, verbose=3)

In [54]:
# Train the model with GridSearch
grid2.fit(X_scaled_train, encoded_y_train.ravel())

Fitting 3 folds for each of 32 candidates, totalling 96 fits


/Users/nebiatadugna/opt/anaconda3/envs/EnvBootcamp/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=10)]: Using backend LokyBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  12 tasks      | elapsed:   12.1s
[Parallel(n_jobs=10)]: Done  96 out of  96 | elapsed:   41.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=10,
       param_grid={'C': [500, 600, 700, 800, 1000, 1100, 1200, 1300], 'gamma': [1e-16, 1e-15, 1e-14, 1e-13]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [55]:
grid2

GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=10,
       param_grid={'C': [500, 600, 700, 800, 1000, 1100, 1200, 1300], 'gamma': [1e-16, 1e-15, 1e-14, 1e-13]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [56]:
sorted(grid2.cv_results_.keys())


['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'mean_train_score',
 'param_C',
 'param_gamma',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split0_train_score',
 'split1_test_score',
 'split1_train_score',
 'split2_test_score',
 'split2_train_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score',
 'std_train_score']

In [57]:
print(grid2.best_params_)
print(grid2.best_score_)

{'C': 500, 'gamma': 1e-16}
0.8840358573335877


# Save the Model

In [58]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'nebiat.sav'
joblib.dump(model2, filename)

['nebiat.sav']